schema_version: '2.0'
directory_name: fracton
description: ''
semantic_scope:
- entropy_dynamics
- bifractal_computation
- computational_modeling_language
files:
- __init__.py
child_directories:
- core
- examples
- lang
- tools
