schema_version: '2.0'
directory_name: ''
description: Handles Ollama AI integration for enhanced metadata generation and semantic
  analysis.
semantic_scope:
- ai/ml
- testing
- documentation
- implementation
files:
- .gitignore
- ARCHITECTURE.md
- LICENSE
- pytest.ini
- README.md
- requirements-dev.txt
- ROADMAP.md
- SETUP.md
- setup.py
- SPEC.md
- STATUS.md
- validate_fracton.py
child_directories:
- fracton
- tests
