schema_version: '2.0'
directory_name: lang
description: The lang directory is a Python package containing lang modules and functionality.
  It provides a structured collection of related code organized for easy import and
  use.
semantic_scope:
- lang
files:
- __init__.py
- compiler.py
- context.py
- decorators.py
- primitives.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 6
  directory_count: 0
  primary_file_types:
    .py: 5
    .yaml: 1
