schema_version: '2.0'
directory_name: lang
description: Handles language AI integration for enhanced metadata generation and semantic
  analysis.
semantic_scope:
- ai/ml
- dependency_resolution
- machine_learning
- data_integration
files:
- __init__.py
- compiler.py
- context.py
- decorators.py
- primitives.py
child_directories: []
