schema_version: '2.0'
directory_name: roadmaps
description: The roadmaps directory contains documentation and reference materials
  for roadmaps. It includes explanatory documents that help users understand and work
  with this component.
semantic_scope:
- roadmaps
files:
- fracton_roadmap.md
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 2
  directory_count: 0
  primary_file_types:
    .md: 1
    .yaml: 1
