schema_version: '2.0'
directory_name: .cip
description: The .cip directory contains configuration and metadata files for .cip.
  It houses YAML definitions, configuration templates, and structured data that define
  system behavior.
semantic_scope:
- .cip
files:
- core.yaml
- instructions_v2.0.yaml
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .yaml: 3
