schema_version: '2.0'
directory_name: examples
description: Fracton SDK examples and demonstrations including GAIA integration patterns,
  implementation guides, and practical applications of fractal computation systems.
semantic_scope:
- code_examples
- demonstrations
- integration_patterns
- gaia_integration
- implementation_guides
- practical_applications
- tutorials
- sample_code
files:
- __init__.py
- gaia_integration.py
child_directories: []
