schema_version: '2.0'
directory_name: examples
description: This directory implements Fracton-based GAIA integration for enhanced
  recursive cognition and infodynamics research applications.
semantic_scope:
- ai/ml
- infodynamics
- recursive computation
- cognitive modeling
- computational linguistics
files:
- __init__.py
- gaia_integration.py
child_directories: []
