schema_version: '2.0'
directory_name: core
description: The core directory provides a comprehensive runtime engine for Fracton
  recursive functions, implementing intelligent function dispatch, bifractal tracing,
  and memory field management to support high-performance infodynamics computing.
semantic_scope:
- ai/ml
- gpu-accelerated computation
- entropy-aware routing
- recursive execution
- dynamic memory management
files:
- __init__.py
- bifractal_trace.py
- entropy_dispatch.py
- gpu_accelerated_memory_field.py
- memory_field.py
- recursive_engine.py
child_directories: []
